export type {
  Cn23PathParams,
  Cn23Result,
  Cn23Response,
  DeclarationPathParams,
  DeclarationResult,
  DeclarationResponse,
  RegisterPathParams,
  RegisterResult,
  RegisterResponse,
  Sticker100PathParams,
  Sticker100QueryParams,
  Sticker100Result,
  Sticker100Response,
  Sticker100A4PathParams,
  Sticker100A4QueryParams,
  Sticker100A4Result,
  Sticker100A4Response,
} from './generated';
