export type {
  AvailableTimeSlotsQueryParams,
  AvailableTimeSlotsResult,
  AvailableTimeSlotsResponse,
  RegisterBranchRequestBody,
  RegisterBranchResult,
  RegisterBranchResponse,
  RegisterBranch2RequestBody,
  RegisterBranch2PathParams,
  RegisterBranch2Result,
  RegisterBranch2Response,
  RegisterBranch3PathParams,
  RegisterBranch3Result,
  RegisterBranch3Response,
  RegisterPickupRequestBody,
  RegisterPickupResult,
  RegisterPickupResponse,
  RegisterPickup2RequestBody,
  RegisterPickup2PathParams,
  RegisterPickup2Result,
  RegisterPickup2Response,
  RegisterPickup3PathParams,
  RegisterPickup3Result,
  RegisterPickup3Response,
  RegistersListPathParams,
  RegistersListResult,
  RegistersListResponse,
} from './generated';
